config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  get "dashboard", to: "pages#dashboard"
  resources :offers do
    resources :bookings, only: [:index, :create, :show, :destroy]
  end
  delete "/bookings/:id/deny", to: "bookings#deny", as: :deny
  get "/bookings/:id/accept", to: "bookings#accept", as: :accept
  patch "offers/:id/like", to: "offers#like", as: :like
  patch "offers/:id/dislike", to: "offers#dislike", as: :dislike
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :offer
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  include PgSearch
  has_many :bookings, dependent: :destroy
  mount_uploader :photo, PhotoUploader
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  pg_search_scope :global_search,
    against: [:address, :description, :company_name ],
    using: {
      tsearch: { prefix: true }
    }

  acts_as_votable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :offer, dependent: :destroy
  has_many :bookings, dependent: :destroy
  acts_as_voter

  def likes
    self.votes.up.for_type(Offer)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @offer = Offer.find(params[:offer_id])
    authorize @offer, :destroy?
    @bookings = @offer.bookings
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.user = current_user #for sen an email

    authorize @booking
    @booking.status = "accepted"
    @booking.save
    redirect_to offer_bookings_path(@booking.offer_id)
  end

  def deny
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to offer_bookings_path(@booking.offer_id)
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.offer = Offer.find(params[:offer_id])
    authorize @booking
    @booking.user = current_user
    if @booking.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  # def show
  # end

  # def edit
  # end

  # def update
  #   @booking = Booking.new(booking_params)
  #   @booking.update
  # end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to dashboard_path
  end

  private

  def booking_params
    params.require(:booking).permit(:description, :date, :status)
  end


end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      sql_query = " \
        offers.company_name ILIKE :query \
        OR offers.description ILIKE :query \
        OR offers.address ILIKE :query \
      "
      @offers = Offer.where(sql_query, query: "%#{params[:query]}%")
      clean_map
    else
      @offers = Offer.all
      clean_map
    end
  end

  def show
    @offer = Offer.find(params[:id])
    @booking = Booking.new
    authorize @offer
  end

  def new
    @offer = Offer.new
    authorize @offer
  end

  def edit
    @offer = Offer.find(params[:id])
    authorize @offer
  end

  def update
    @offer = Offer.find(params[:id])
    @offer.update(offer_params)
    redirect_to offer_path(@offer)
    authorize @offer
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.user = current_user
    authorize @offer
    if @offer.save
      redirect_to offer_path(@offer)
    else
      render :new
    end
  end

  def destroy
    @offer = Offer.find(params[:id])
    authorize @offer
    @offer.destroy
    redirect_to offers_path
  end

  def like
    @offer = Offer.find(params[:id])
    authorize @offer
    @offer.liked_by current_user
    redirect_to offers_path
  end

  def dislike
    @offer = Offer.find(params[:id])
    authorize @offer
    @offer.disliked_by current_user
    redirect_to offers_path
  end

private

  def offer_params
    params.require(:offer).permit(:company_name, :address, :description, :price, :photo)
  end

  def clean_map
    @offers = @offers.where.not(latitude: nil, longitude: nil)

    @markers = @offers.map do |offer|
      {
        lat: offer.latitude,
        lng: offer.longitude,
      infoWindow: { content: render_to_string(partial: "/offers/map_box", locals: { offer: offer }) }
      }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   skip_before_action :authenticate_user!, only: [:home, :offers]

   def dashboard
     @bookings= Booking.where(user_id: current_user.id)
     @offers = current_user.likes.map { |like| Offer.find(like.votable_id) }
   end

  def home
    @offers = Offer.all
    @offer = Offer.new
  end

  def wishlist
    @offers = current_user.likes.map { |like| Offer.find(like.votable_id) }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="product">
  <div class="pros-header">
    <% if @offer.photo.file.nil? %>
      <% @url = "https://images.unsplash.com/photo-1506967236291-3d3c4ad88abd?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=8966dd3034be8631151ec07601acfa02&auto=format&fit=crop&w=2849&q=80" %>
    <% else %>
      <% @url = cl_image_path @offer.photo %>
    <% end %>
    <div class="photo-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= @url %>')">
      <div class="photo-banner-content">
        <h1 id="offer-banner-title">Liste des rendez-vous de <%= @offer.company_name %></h1>
        <p></p>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="content-bloc">
    <ul class="booking-list">
      <% @bookings.each do |booking| %>
        <div class="booking-element">
          <div class= "row date-font">
            <li><strong><%= booking.date %></strong></li>
          </div>
          <div class="row flex-body">
            <div class="booking-info">
              <li><strong><%= User.find(booking.user_id).last_name %> <%= User.find(booking.user_id).first_name %></strong></li>
              <li><p><strong>Tel: </strong><%= User.find(booking.user_id).phone_number %><strong> | Email: </strong><%= User.find(booking.user_id).email %></p></li>
              <li><p><strong>Commentaires: </strong><%= booking.description %></p></li>
            </div>
          </div>
          <div class="row status-font" id="status">
            <li><strong><em><%= booking.status == "<pend></pend>ing" ? "en attente" : "confirmé" %></em></strong></li>
          </div>
          <div class="row action-rdv">
            <% if booking.status == "<pend></pend>ing" %>
              <div class="row-status">
                <li>
                  <%= link_to(accept_path(booking), { method: :get, data: { confirm: "Confirmer le rendez-vous ?" } }) do %>
                    <i class="fa fa-check-square"></i>
                  <% end %>
                </li>
              </div>
              <div class="row-status">
                <li><p> | </p></li>
              </div>
              <div class="row-status">
                <li>
                  <%= link_to(deny_path(booking), { method: :delete, data: { confirm: "Êtes-vous sûr ?" } }) do %>
                    <i class="fa fa-trash-alt"></i>
                  <% end %>
                </li>
              </div>
              <% else %>
              <div class="row-status">
                <li>
                  <%= link_to(deny_path(booking), { method: :delete, data: { confirm: "Êtes-vous sûr ?" } }) do %>
                    <i class="fa fa-trash-alt"></i>
                  <% end %>
                </li>
              </div>
              <div class="row-status">
                <li><p> | </p></li>
              </div>
              <div class="row-status">
                <li>
                  <%= mail_to booking.user.email, cc: @offer.user.email, subject: "[RailRoad] Confirmation de rendez-vous", body: "Votre rendez-vous du #{booking.date} avec #{@offer.company_name} est confirmé ! Merci d'avoir choisi RAIL ROAD :-)" do %>
                    <i class="fa fa-envelope"></i>
                  <% end %>
                </li>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </ul>
    <div class="row-btn">
      <div class="return-btn-position">
        <%= link_to "retour", offer_path(@offer), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Railroad</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
      <div class="wrapper <%= "marged-top min-height-100vh" unless params[:action] == "home" %>">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag "map" %>
  </body>
</html>

app/views/offers/_map_box.html.erb
<div class="container-wb">
  <div class="window-box-title">
    <h3><strong> <%= offer.company_name %></strong></h3>
  </div>

  <div class="Window-box-content">
    <p><strong>Address:</strong> <%= offer.address %></p>
    <p><strong>Prix: <%= offer.price %> €</strong></p>
    <p><%= offer.description.first(140) %>...</p>
  </div>

  <div id="button-box">
    <%= link_to "voir", offer_path(offer) %>
  </div>
</div>

app/views/offers/edit.html.erb
<div class= card-banner>
<div class="container ">
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
          <div class="box">
          <h1 class="white-bold-title">A remplir:</h1>
          <%= simple_form_for @offer do |f| %>
            <%= f.input :company_name %>
            <%= f.input :address %>
            <%= f.input :description %>
            <%= f.input :price %>
            <%= f.input :photo %>
            <%= f.input :photo_cache, as: :hidden %>
            <%= f.submit "OK", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/offers/index.html.erb
<div class="wrapper">
  <div class="product">
    <div class="pros-header">
      <div class="photo-banner" style="background-image: linear-gradient(rgba(0,0,0,0.8), rgba(0,0,0,0.3)), url(<%= asset_path('Unsp.jpg') %>">
        <div class="col-sm-6 col-sm-offset-3 col-margin">
          <h2 id="white"><strong>RAILROAD</strong></h2>
          <h5 id="white" style="padding-top: 20px">Construisons ensemble votre projet d'avenir </h5>
                <%= form_tag  offers_path, method: :get do %>
                  <%= text_field_tag :query,
                    params[:query],
                    class: "form-control",
                    placeholder: "cherchez ici un conseiller, une entreprise..."
                  %>
            <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-6 col-sm-8">
      <div class="cards-container">
        <% @offers.each do |offer| %>
          <% if offer.photo.file.nil? %>
            <% url =  "https://images.unsplash.com/photo-1506967236291-3d3c4ad88abd?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=8966dd3034be8631151ec07601acfa02&auto=format&fit=crop&w=2849&q=80"%>
          <% else %>
            <% url =  cl_image_path offer.photo, height: 300, width: 400, crop: :fill%>
          <% end %>
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('<%= url %>')">
            <% if policy(offer).edit? %>
              <%= link_to "edit", edit_offer_path(offer), class: "btn btn-primary card-btn first-layer" %>
              <%= link_to offer_path(offer), method: :delete do %>
                <i class="fa fa-trash-alt first-layer"></i>
              <% end %>
            <% end %>
            <div class="card-description">
              <h2><%= offer.company_name %></h2>
              <p><%= offer.description.first(70) %>...</p>
            </div>
            <%= link_to "", offer_path(offer), class: "card-link"%>
            <% if offer.get_likes.where(voter_id: current_user).count == 0 %>
              <%= link_to like_path(offer), method: :patch, class: "card-like-link" do%>
                <i class="far fa-heart"></i>
              <% end %>
            <% else %>
              <%= link_to dislike_path(offer), method: :patch, class: "card-like-link" do %>
                <i class="fas fa-heart"></i>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="map-container col-xs-6 col-sm-4 padding-left-0">
      <div id="map" data-markers="<%= @markers.to_json %>"></div>
    </div>
  </div>
</div>

app/views/offers/new.html.erb
<div class= card-banner>
<div class="container ">
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
          <div class="box">
          <h1 class="white-bold-title">A remplir:</h1>
          <%= simple_form_for @offer do |f| %>
            <%= f.input :company_name %>
            <%= f.input :address %>
            <%= f.input :description %>
            <%= f.input :price %>
            <%= f.input :photo %>
            <%= f.input :photo_cache, as: :hidden %>
            <%= f.submit "OK", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/offers/show.html.erb
<div class="product">
  <div class="pros-header">
    <% if @offer.photo.file.nil? %>
      <% @url = "https://images.unsplash.com/photo-1506967236291-3d3c4ad88abd?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=8966dd3034be8631151ec07601acfa02&auto=format&fit=crop&w=2849&q=80" %>
    <% else %>
      <% @url = cl_image_path @offer.photo %>
    <% end %>
    <div class="photo-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= @url %>')">
      <div class="photo-banner-content">
        <h1 id="offer-banner-title"><%= @offer.company_name %></h1>
        <p><%= @offer.user.phone_number %> | <%= @offer.user.email %> | <%= @offer.address %></p>
      </div>
    </div>
  </div>
</div>
<div class="main-container container">
  <div class="row">
    <div class="col-xs-8">
      <div class= "description-block">
        <%= link_to "retour", offers_path, :class => "neww-button" %>
        <h2 class="offre strong">Notre offre</h2>
        <p class="offredesc"><%= @offer.description %></p>
      </div>
    </div>

    <div class="block-container col-xs-4">
      <div class="booking-block">
        <h2>Réserver cette offre:</h2>
        <h3><%= @offer.company_name %></h3>
        <p>Prix:<%= @offer.price %>€</p>
        <%= simple_form_for [@offer, @booking] do |f| %>
        <%= f.input :date,  enableTime: true, dateformat: "Y-m-d H:i",required: false, as: :string, input_html: {class: " form-control datepicker "} %>
        <%= f.input :description, label: "Commentaires", placeholder: "Décrivez vos besoins en orientation", input_html: { maxlength: 300 } %>
        <%= f.submit "réserver", class: "btn btn-success element-large" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="wrapper">
  <div>
    <div class="photo-banner" style = "background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/photo-1511832752475-638d191345e5?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=0d69a2aa48c6eed28f94cc24b083cc09&auto=format&fit=crop&w=684&q=80')">
      <div class="h1Wishlist">
        <h1 id="offer-banner-title">Ma Wishlist: </h1>
      </div>
      <div>
        <% if @offers.empty? %>
          <p class="text-whishlist-banner">Vous n'avez liké aucune offre pour le moment...</p>
        <% else %>
          <div class="row">
            <div class="col-sm-8 col-sm-offset-2">
              <div class="row">
                <% @offers.each do |offer| %>
                <div class="col-sm-4">
                  <div class="wishlist card">
                    <div class="title"><%=offer.company_name %></div>
                    <div class="subtitle"><%=offer.address %></div>
                    <div class="subtitle"><%=offer.price %> €</div>
                    <div><%= link_to 'Revoir cette offre', offer_path(offer), :class => "btn btn-success" %></div>
                    <i class="fas fa-heart"></i>
                  </div>
                </div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="content-bloc">
      <ul class="booking-list">
        <h1>Mes rendez-vous:</h1>
          <% @bookings.each do |booking| %>
            <div class="booking-element">
              <div class= "row date-font">
                <li><strong><%= booking.date %></strong></li>
              </div>
              <div class="row flex-body">
                <div class="booking-info">
                  <li><strong><%= User.find(booking.offer.user_id).last_name %> <%= User.find(booking.offer.user_id).first_name %></strong></li>
                  <li><p><strong>Tel: </strong><%= User.find(booking.offer.user_id).phone_number %><strong> | Email: </strong><%= User.find(booking.offer.user_id).email %></p></li>
                  <li><p><strong>Commentaires: </strong><%= booking.offer.company_name %></p></li>
                </div>
              </div>
              <div class="row status-font" id="status">
                <li><strong><em><%= booking.status == "<pend></pend>ing" ? "en attente" : "confirmé" %></em></strong></li>
              </div>
              <div class="row action-rdv">
                <div class="row-status">
                  <li>
                    <%= link_to offer_booking_path(booking.offer, booking), method: :delete do %>
                      <i class="fa fa-trash-alt"></i>
                    <% end %>
                  </li>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </ul>
      <div class="row-btn">
        <div class="return-btn-position">
          <%= link_to "retour", offers_path, class: "btn btn-primary" %>
        </div>
      </div>
      </div>
  </div>
</div>
____________________________________________________________________

app/views/pages/home.html.erb
<div class="wrapper">
  <div class="home-banner">
    <h2><strong>BIENVENUE SUR RAILROAD</strong></h2>
    <p>
        <span id="banner-typed-text";"></span>
    </p>

  <%# simple_form_for(@offer) do |f| %>
    <%#f.input :company_name, placeholder: 'company_name' %>
    <%# f.input :address, placeholder: 'address' %>
    <%# f.submit "Go", class: "btn btn-primary" %>
  <%# end %>

  <%= link_to "Voir toutes les offres", offers_path, class: "new-button"%>
</div>


<div class="wrapper" style="padding-bottom: 50px">
  <div class="container">
    <div id="cards-home">
      <div class="text-center">
        <h3 style="padding-bottom: 60px">DES CONSEILS SUR-MESURE</h3>
        <div class="row" style="padding-top: 30px, padding-bottom: 30px">
          <div class="col-sm-3 col-xs-6">
            <%= image_tag 'Artboard 10.svg', height: 80, width: 80, class: "grey"  %>
            <h4 style="padding-top: 10px">Un suivi adapté à chaque profil</h4>
            <p style="padding-top: 15px"><em>Un bilan personnel est réalisé avec l'étudiant pour définir une feuille de route précise</em></p>
          </div>
          <div class="col-sm-3 col-xs-6">
            <%= image_tag 'Artboard 9.svg', height: 80, width: 80, class: "grey"  %>
            <h4 style="padding-top: 10px">Des conseillers dimplômés d'Etat    </h4><p style="padding-top: 15px"><em>Des conseillers diplomés d'Etat qui viennent du secteur privé comme du secteur public</em></p>
          </div>
          <div class="col-sm-3 col-xs-6">
            <%= image_tag 'Artboard 15.svg', height: 80, width: 80, class: "grey"  %>
            <h4 style="padding-top: 10px">Un parcours 100% digitalisé</h4><p style="padding-top: 15px"><em>Un suivi multi-supports, facile d'utilisation et accessible à chaque instant</em></p>
          </div>
          <div class="col-sm-3 col-xs-6">
            <%= image_tag 'Artboard 11.svg', height: 80, width: 80, class: "grey"  %>
            <h4 style="padding-top: 10px"><em>Une couverture sur tout le territoire</h4><p style="padding-top: 15px">Un service souhaité par les ministères de l'Education Nationale et de l'Enseignement Supérieur</em></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!--


  <button id="sweet-alert-demo" class="btn btn-primary">Click me!</button>
  <#%= select_tag "timezone", options_from_collection_for_select(

        ActiveSupport::TimeZone.all.
        map { |tz| tz.tzinfo }.
        sort_by { |tzinfo| tzinfo.name },
        :name, :name),
        class: 'select2' %> -->
</div>

app/views/pages/index.html.erb
<h1>Our index of offers</h1>
<ul>
  <% Offer.all.each do |offer| %>
    <li><%= offer.company_name %></li>
    <li><%= offer.address %></li>
    <li><%= offer.description %></li>
    <li><%= offer.price %></li>
    <li><%= offer.user.first_name %></li>
    <li><%= offer.user.last_name %></li>
  <% end %>
</ul>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    © Railroad 2018
  </div>
  <div class="footer-contact">
    <em>    Contact us at contact@railroad.com</em>
  </div>
  <div class="footer-links footer-links a:hover">
    <a href="https://github.com/PaulaVandemeulebroucke/railroad"><i class="fa fa-github"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top <%= "navbar-wagon-white " if !current_page?(root_path) %>">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
      <!-- Links when logged in -->
      <%= link_to "Espace pro", new_offer_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to dashboard_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "My Bookings") %>
              <% end %>
            </li>
            <li>

              <% if current_user.offer.present? %>
                <%= link_to offer_bookings_path(current_user.offer) do %>
                  <i class="fa fa-user"></i> <%= t(".profile", default: "My Offer") %>
                <% end %>
              <% end %>

            </li>
            <li>

              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>
<%= render 'shared/flashes' %>